server:
  port: 8080

spring:
  datasource:
    username: root
    password: javajava
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
#    drop-first: true

indexing-settings:
  sites:
    #    - url: https://www.lenta.ru
    #      name: Лента.ру
#        - url: https://skillbox.ru/
#          name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://nikoartgallery.com/
      name: Niko Art Gallery
#    - url: https://www.svetlovka.ru/
#      name: Светловка
#    - url: https://sendel.ru/
#      name: Sendel